forwarder:
  sync:
    user_port: 5005
    user_hostname: "localhost"
    use_grpc: false
    predict_route: "/v1/completions"
    healthcheck_route: "/health"
    batch_route: null
    model_engine_unwrap: true
    serialize_results_as_string: true
    forward_http_status: true
    extra_routes: []
  stream:
    user_port: 5005
    user_hostname: "localhost"
    predict_route: "/v1/completions"
    healthcheck_route: "/health"
    batch_route: null
    model_engine_unwrap: true
    serialize_results_as_string: false
    extra_routes: []

  max_concurrency: 100
