forwarder:
  sync:
    user_port: e 5005
    user_hostname: "localhost"
    use_grpc: false
    predict_route: "/predict"
    healthcheck_route: "/readyz"
    batch_route: null
    model_engine_unwrap: true
    serialize_results_as_string: true
    forward_http_status: true
    extra_routes: ["/v1/chat/completions", "/v1/completions"]
  stream:
    user_port: 5005
    user_hostname: "localhost"
    predict_route: "/stream"
    healthcheck_route: "/readyz"
    batch_route: null
    model_engine_unwrap: true
    serialize_results_as_string: false
    extra_routes: ["/v1/chat/completions", "/v1/completions"]
  max_concurrency: 100
