forwarder:
  sync:
    user_port: 5005
    user_hostname: "localhost"
    use_grpc: false
    predict_route: "/predict"
    healthcheck_route: "/readyz"
    batch_route: null
    model_engine_unwrap: true
    serialize_results_as_string: true
    forward_http_status: true
    extra_routes: []  # Legacy field - still supported for backwards compatibility
    # routes: []     # New field - can be used alongside or instead of extra_routes
  stream:
    user_port: 5005
    user_hostname: "localhost"
    predict_route: "/stream"
    healthcheck_route: "/readyz"
    batch_route: null
    model_engine_unwrap: true
    serialize_results_as_string: false
    extra_routes: []  # Legacy field - still supported for backwards compatibility
    # routes: []     # New field - can be used alongside or instead of extra_routes

  max_concurrency: 100
