# syntax=docker/dockerfile:1
ARG VLLM_VERSION=0.10.2
ARG VLLM_BASE_REPO=vllm/vllm-openai
ARG VLLM_BASE_IMAGE=${VLLM_BASE_REPO}:v${VLLM_VERSION}
FROM ${VLLM_BASE_IMAGE} AS base

RUN apt-get update \
    && apt-get install -y wget gdb psmisc dumb-init iproute2 netcat lsof \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    apt-get clean

WORKDIR /workspace

RUN wget https://github.com/peak/s5cmd/releases/download/v2.2.1/s5cmd_2.2.1_Linux-64bit.tar.gz
RUN tar -xvzf s5cmd_2.2.1_Linux-64bit.tar.gz

# symlink python to python3
RUN ln -s /usr/bin/python3 /usr/bin/python

FROM base AS vllm

COPY model-engine/model_engine_server/inference/vllm/vllm_server.py /workspace/vllm_server.py
COPY model-engine/model_engine_server/inference/vllm/init_ray.sh /workspace/init_ray.sh

# Need to override entrypoint from parent image
ENTRYPOINT ["/bin/env"]

FROM base AS vllm_batch

COPY model-engine/model_engine_server/inference/batch_inference/requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt

COPY model-engine /workspace/model-engine
RUN pip install -e /workspace/model-engine
COPY model-engine/model_engine_server/inference/batch_inference/vllm_batch.py /workspace/vllm_batch.py

# Need to override entrypoint from parent image
ENTRYPOINT ["/bin/env"]

FROM base AS vllm_batch_v2

COPY model-engine/model_engine_server/inference/vllm/requirements-batch.txt /workspace/requirements.txt
RUN pip install -r requirements.txt

COPY model-engine /workspace/model-engine
RUN pip install -e /workspace/model-engine
COPY model-engine/model_engine_server/inference/vllm/vllm_batch.py /workspace/vllm_batch.py
COPY model-engine/model_engine_server/inference/vllm/init_ray_batch_inf_v2.py /workspace/init_ray_batch_inf_v2.py

# Some hacky stuff to override ray files
COPY model-engine/model_engine_server/inference/vllm/ray_overrides/_version.py /usr/local/lib/python3.12/dist-packages/ray/_version.py
COPY model-engine/model_engine_server/inference/vllm/ray_overrides/proxier.py /usr/local/lib/python3.12/dist-packages/ray/util/client/server/proxier.py

# Need to override entrypoint from parent image
ENTRYPOINT ["/bin/env"]