# syntax=docker/dockerfile:1
ARG VLLM_VERSION=0.6.2
ARG VLLM_BASE_IMAGE=vllm/vllm-openai:v${VLLM_VERSION}
FROM ${VLLM_BASE_IMAGE} AS base

RUN apt-get update \
    && apt-get install -y wget gdb psmisc dumb-init \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    apt-get clean

WORKDIR /workspace

RUN wget https://github.com/peak/s5cmd/releases/download/v2.2.1/s5cmd_2.2.1_Linux-64bit.tar.gz
RUN tar -xvzf s5cmd_2.2.1_Linux-64bit.tar.gz

# symlink python to python3
RUN ln -s /usr/bin/python3 /usr/bin/python

FROM base AS vllm

COPY model-engine/model_engine_server/inference/vllm/vllm_server.py /workspace/vllm_server.py
COPY model-engine/model_engine_server/inference/vllm/init_ray.sh /workspace/init_ray.sh

# Need to override entrypoint from parent image
ENTRYPOINT ["/bin/env"]

FROM base AS vllm_batch

COPY model-engine/model_engine_server/inference/batch_inference/requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt

COPY model-engine /workspace/model-engine
RUN pip install -e /workspace/model-engine
COPY model-engine/model_engine_server/inference/batch_inference/vllm_batch.py /workspace/vllm_batch.py

# Need to override entrypoint from parent image
ENTRYPOINT ["/bin/env"]

FROM base AS vllm_batch_v2

COPY model-engine/model_engine_server/inference/vllm/requirements-batch.txt /workspace/requirements.txt
RUN pip install -r requirements.txt

COPY model-engine /workspace/model-engine
RUN pip install -e /workspace/model-engine
COPY model-engine/model_engine_server/inference/vllm/vllm_batch.py /workspace/vllm_batch.py

# Need to override entrypoint from parent image
ENTRYPOINT ["/bin/env"]