# Same as Black.
line-length = 100
target-version = "py310"
lint.ignore = ["E501"]
exclude = ["gen", "alembic"]

[lint.per-file-ignores]
"model-engine/model_engine_server/inference/forwarding/celery_forwarder.py" = ["E402"]