#!/usr/bin/env python3
"""
Generate OpenAPI schemas for client code generation.

This script generates two versions of the OpenAPI schema:
1. openapi.json - Native OpenAPI 3.1 schema as generated by FastAPI
2. openapi-3.0.json - Processed schema compatible with OpenAPI Generator 6.x

Usage:
    python scripts/generate_openapi_schemas.py [output_dir]

The output directory defaults to 'specs/' in the model-engine directory.
"""
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add the model-engine package to the path
sys.path.insert(0, str(Path(__file__).parent.parent))

# Set required environment variables before importing app
os.environ.setdefault("GIT_TAG", "dev")
os.environ.setdefault("OMP_NUM_THREADS", "1")


def main():
    output_dir = sys.argv[1] if len(sys.argv) > 1 else "specs"
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Import after setting environment variables
    from model_engine_server.api.app import get_openapi_schema

    # Generate OpenAPI 3.1 schema (native FastAPI output)
    print("Generating OpenAPI 3.1 schema...")
    schema_31 = get_openapi_schema(openapi_30_compatible=False)
    schema_31_path = output_path / "openapi.json"
    with open(schema_31_path, "w") as f:
        json.dump(schema_31, f, indent=2)
    print(f"  Written to: {schema_31_path}")

    # Generate OpenAPI 3.0 compatible schema
    print("Generating OpenAPI 3.0 compatible schema...")
    schema_30 = get_openapi_schema(openapi_30_compatible=True)
    schema_30_path = output_path / "openapi-3.0.json"
    with open(schema_30_path, "w") as f:
        json.dump(schema_30, f, indent=2)
    print(f"  Written to: {schema_30_path}")

    # Write metadata
    metadata = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git_tag": os.environ.get("GIT_TAG", "unknown"),
        "files": {
            "openapi.json": "OpenAPI 3.1 (native FastAPI output)",
            "openapi-3.0.json": "OpenAPI 3.0 compatible (for code generators)",
        },
    }
    metadata_path = output_path / "metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"  Metadata written to: {metadata_path}")

    print("\nDone!")


if __name__ == "__main__":
    main()
