FROM lmsysorg/sglang:v0.4.6.post5-cu124

# These aren't all needed but good to have for debugging purposes
RUN apt-get -yq update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  build-essential \
  apt-utils \
  dumb-init \
  git \
  gcc \
  ssh \
  htop \
  iftop \
  vim \
  apt-transport-https \
  ca-certificates \
  gnupg \
  curl \
  zlib1g-dev \
  libjpeg-dev \
  libsm6 \
  libxext6 \
  libxrender-dev \
  libgl1-mesa-glx \
  libglib2.0-0 \
  libgtk2.0-dev \
  libssl-dev \
  libbz2-dev \
  libreadline-dev \
  libsqlite3-dev \
  wget \
  llvm \
  libncurses5-dev \
  libncursesw5-dev \
  xz-utils \
  tk-dev \
  libffi-dev \
  liblzma-dev \
  python3-openssl \
  moreutils \
  libcurl4-openssl-dev \
  libssl-dev \
  python3-dev \
  gcc \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get clean

# Copy model files into /root/model_files
ARG S5CMD_VERSION=2.2.2
RUN wget https://github.com/peak/s5cmd/releases/download/v${S5CMD_VERSION}/s5cmd_${S5CMD_VERSION}_linux_amd64.deb && \
    dpkg -i s5cmd_${S5CMD_VERSION}_linux_amd64.deb && \
    rm s5cmd_${S5CMD_VERSION}_linux_amd64.deb

# Copy sglang startup script
COPY sglang-startup-script.py /root/sglang-startup-script.py
