{{- if .Values.endpointGc.enabled }}
{{- $app := include "modelEngine.endpointgcname" . }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $app }}
  labels:
    {{- include "modelEngine.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.endpointGc.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: {{ .Values.endpointGc.activeDeadlineSeconds }}
      template:
        metadata:
          annotations:
            ad.datadoghq.com/main.logs: '[{"service": "{{ $app }}", "source": "python"}]'
            sidecar.istio.io/inject: "false"
          labels:
            {{- include "modelEngine.labels" . | nindent 12 }}
            tags.datadoghq.com/service: {{ $app }}
        spec:
          restartPolicy: Never
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: main
              {{- with .Values.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ .Values.image.gatewayRepository }}:{{ .Values.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - dumb-init
                - --
              args:
                - python
                - -m
                - model_engine_server.entrypoints.endpoint_gc
                - --broken-scale-to-zero-days
                - {{ .Values.endpointGc.broken.scaleToZeroDays | quote }}
                - --broken-delete-days
                - {{ .Values.endpointGc.broken.deleteDays | quote }}
                - --idle-scale-to-zero-days
                - {{ .Values.endpointGc.idle.scaleToZeroDays | quote }}
                - --idle-delete-days
                - {{ .Values.endpointGc.idle.deleteDays | quote }}
                - --action-cap
                - {{ .Values.endpointGc.actionCap | quote }}
                {{- if .Values.endpointGc.actionsEnabled }}
                - --act
                {{- end }}
              resources:
                {{- toYaml .Values.endpointGc.resources | nindent 16 }}
              {{- include "modelEngine.endpointGcEnv" . | indent 14 }}
              {{- include "modelEngine.volumeMounts" . | indent 14 }}
          automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
          serviceAccountName: {{ include "modelEngine.fullname" . }}
          {{- include "modelEngine.volumes" . | indent 10 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
