{{- if and (.Values.imageBuilderServiceAccount) (.Values.imageBuilderServiceAccount.create) }}
{{- $serviceAccountNamespaces := (include "modelEngine.serviceAccountNamespaces" . | fromYaml) }}
{{- $annotations := .Values.imageBuilderServiceAccount.annotations }}
{{- $labels := include "modelEngine.labels" . }}
{{- range $namespace := (index $serviceAccountNamespaces "namespaces") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko 
  namespace: {{- printf " %s" $namespace }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
