{{- $serviceAccountName := include "modelEngine.fullname" . }}
{{- $serviceAccountNamespaces := (include "modelEngine.serviceAccountNamespaces" . | fromYaml) }}
{{- $annotations := .Values.serviceAccount.annotations }}
{{- $labels := include "modelEngine.labels" . }}
{{- range $namespace := (index $serviceAccountNamespaces "namespaces") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- printf " %s" $serviceAccountName }}
  namespace: {{- printf " %s" $namespace }}
  labels:
    {{- $labels | nindent 4 }}
  {{- if or $annotations .Values.azure .Values.gcp }}
  annotations:
    {{- with $annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.azure }}
    azure.workload.identity/client-id: {{ $.Values.azure.client_id }}
    {{- end }}
    {{- if $.Values.gcp }}
    {{- if $.Values.gcp.iam_service_account }}
    iam.gke.io/gcp-service-account: {{ $.Values.gcp.iam_service_account }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- if $.Values.azure }}
imagePullSecrets:
  - name: egp-ecr-regcred
{{- end }}
automountServiceAccountToken: {{ $.Values.automountServiceAccountToken }}
---
{{- end }}
