ARG ECR_REGISTRY=022465994601.dkr.ecr.us-west-2.amazonaws.com
FROM ${ECR_REGISTRY}/golden/chainguard/python-fips:3.11-dev
WORKDIR /workspace
USER root

RUN apk update && apk add \
            htop \
            dumb-init \
            libssh \
            openssh-client \
            iftop \
            curl \
            curl-dev \
            procps \
            libcurl-openssl4 \
            vim \
            kubectl \
            jq \
            gcc \
            glibc-dev \
            python-3.11-dev \
            libffi-dev \
            openssl-dev \
            build-base \
            postgresql-dev \
            libpq-16

RUN curl -Lo /bin/aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.7.11/aws-iam-authenticator_0.7.11_linux_amd64 && \
    chmod +x /bin/aws-iam-authenticator

RUN pip install pip==24.2
RUN chmod -R 777 /workspace

RUN pip install awscli==1.34.28 --no-cache-dir

WORKDIR /workspace/model-engine/
COPY model-engine/requirements-test.txt /workspace/model-engine/requirements-test.txt
COPY model-engine/requirements.txt /workspace/model-engine/requirements.txt
COPY model-engine/requirements_override.txt /workspace/model-engine/requirements_override.txt
RUN pip install -r requirements-test.txt --no-cache-dir
RUN pip install -r requirements.txt --no-cache-dir
RUN pip install -r requirements_override.txt --no-cache-dir
COPY model-engine/setup.py /workspace/model-engine/setup.py
COPY model-engine/model_engine_server /workspace/model-engine/model_engine_server
RUN pip install -e .

COPY integration_tests /workspace/integration_tests

WORKDIR /workspace
ENV PYTHONPATH=/workspace
ENV WORKSPACE=/workspace

USER nonroot

EXPOSE 5000
